services:
  jupyter_notebook:
    build:
      context: .
    ports:
      - 8888:8888
    volumes:
      - ./data:/home/jovyan/data
      - ./notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./config:/home/jovyan/config
      - ./assets:/home/jovyan/notebooks/assets
    env_file:
      - .env