landing:
  init_turn:
    thres_peaks: 0.75
    min_dist_peaks: 0.1
    thres_lows: 0.75
    min_dist_lows: 5
  toggle_search:
    vertical_speed:
      thres_peaks: 0.25
      min_dist_peaks: 0.1
      thres_lows: 0.35
      min_dist_lows: 5
    first_derivative:
      thres_peaks: 0.70
      min_dist_peaks: 1
      thres_lows: 0.25
      min_dist_lows: 1
  front_riser:
    glide_ratio:
      thres_peaks: 0.5
      min_dist_peaks: 1
      thres_lows: 0.85
      min_dist_lows: 5
    second_derivative:
      thres_peaks: 0.25
      min_dist_peaks: 1
      thres_lows: 0.25
      min_dist_lows: 1
  rollout:
    vertical_speed:
      thres_peaks: 0.5
      min_dist_peaks: 0.1
      thres_lows: 0.75
      min_dist_lows: 0.1
    first_derivative:
      thres_peaks: 0.25
      min_dist_peaks: 1
      thres_lows: 0.25
      min_dist_lows: 1
    second_derivative:
      thres_peaks: 0.25
      min_dist_peaks: 1
      thres_lows: 0.25
      min_dist_lows: 1
  stop:
    thres_peaks: 0.5
    min_dist_peaks: 0.1
    thres_lows: 0.75
    min_dist_lows: 0.1

exit:
  elevation:
    thres_peaks: 0.9
    min_dist_peaks: 1
    thres_lows: 0.75
    min_dist_lows: 5
  horz_speed:
    thres_peaks: 0.6
    min_dist_peaks: 2
    thres_lows: 0.4
    min_dist_lows: 2
  vert_speed:
    thres_peaks: 0.4
    min_dist_peaks: 2
    thres_lows: 0.7
    min_dist_lows: 2
    
pond:
  horz_speed:
    thres_peaks: 0.6
    min_dist_peaks: 100
    thres_lows: 0.75
    min_dist_lows: 5