visualizations:
  exit_overview:
    title: "Exit Overview"
    description: "This visualization provides an overview of data from a skydive, starting when the jumper exited the plane."
    details:
      - label: "Metrics"
        content: "Elevation, horizontal speed, vertical speed, dive angle, and glide ratio."
      - label: "X-axis"
        content: "Options include Horizontal distance, Time, and Distance."
    parameter_options: ['Elevation', 'Vertical speed', 'Glide ratio', 'Horizontal speed', 'Dive angle']
    parameter_default_options: ['Elevation', 'Vertical speed']
    x_axis_options: ['Horizontal distance', 'Time', 'Distance']

  landing_overview:
    title: "Landing Overview"
    description: "This visualization offers a comprehensive overview of your skydive swoop landing, providing valuable insights into your maneuver."
    details:
      - label: "Metrics"
        content: "Elevation, horizontal speed, vertical speed, dive angle, and glide ratio."
      - label: "Events Indicators"
        content: "Vertical lines provide additional information about certain events."
    parameter_options: ['Elevation', 'Vertical speed', 'Glide ratio', 'Horizontal speed', 'Dive angle']
    parameter_default_options: ['Elevation', 'Vertical speed']
    x_axis_options: ['Horizontal distance', 'Time', 'Distance']
    key_event_type: 'landing'

  horizontal_speed:
    title: "Horizontal Speed"
    description: "Understand the dynamics of your skydive swoop landing with our horizontal speed plot."
    details:
      - label: "Speed Profile"
        content: "The plot illustrates your horizontal speed, showing velocity changes."
    x_axis_options: ['Horizontal distance', 'Time', 'Distance']

  side_view:
    title: "Side View Of Flight Path"
    description: "Examine the nuances of your skydive swoop landing with our side view plot visualization."
    details:
      - label: "Flight Path Profile"
        content: "A profile view of your flight path, offering a clear observation of the landing’s rollout."
    x_axis_options: ['Horizontal distance', 'Time', 'Distance']
    key_event_type: 'landing'

  overhead_view:
    title: "Overhead View Of Flight Path"
    description: "Gain a unique perspective on your skydive swoop landing with our overhead view visualization."
    details:
      - label: "Flight Trajectory"
        content: "Your flight path is plotted, giving you a bird’s-eye view of your skydive."
    key_event_type: 'landing'

  map_2d:
    title: "2D Map"
    description: "Explore the intricacies of your skydive swoop landing with our detailed 2D map visualization."
    details:
      - label: "Flight Path"
        content: "Your flight trajectory is clearly marked on the map, giving you a top-down view of your skydive."
    key_event_type: 'pattern'

  map_3d:
    title: "3D Map"
    description: "Dive into the details of your skydive swoop landing with our immersive 3D map visualization."
    details:
      - label: "Flight Path"
        content: "Your flight trajectory is vividly overlaid on high-resolution satellite imagery, providing a real-world context to your skydive."
    key_event_type: 'landing'